
spring:
  application:
    name: zuul
  rabbitmq:
        host: 192.168.52.131
        port: 5672
        username: admin
        password: admin

server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

#手动启用重试
zuul:
  retryable: true

#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500

#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream